### ISSUE TITLE
Crash with metadata.nameX

### ISSUE THREAD

**Issue by lbodor** [jrhouston/tfk8s#29]
v0.1.7 crashes with

```
apiVersion: v1
kind: Foo
metadata:
  nameX: foo
```
but works with
```
apiVersion: v1
kind: Foo
metadata:
  name: foo
```

```
panic: not a string

goroutine 1 [running]:
runtime/debug.Stack(0xc0001659e0, 0x5b86a0, 0x62a200)
	runtime/debug/stack.go:24 +0x9f
main.capturePanic()
	github.com/jrhouston/tfk8s/tfk8s.go:219 +0x76
panic(0x5b86a0, 0x62a200)
	runtime/panic.go:965 +0x1b9
github.com/zclconf/go-cty/cty.Value.AsString(0x0, 0x0, 0x0, 0x0, 0x754ec0, 0x3)
	github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1251 +0x1a5
main.yamlToHCL(0x62f928, 0xc00016c120, 0x5c0ce0, 0xc00007d9b0, 0x0, 0x0, 0x0, 0x0, 0x62f928, 0xc00016c120, ...)
	github.com/jrhouston/tfk8s/tfk8s.go:110 +0x331
main.YAMLToTerraformResources(0x62d0a8, 0xc000010010, 0x0, 0x0, 0x0, 0x0, 0x20, 0xc000020b8a, 0xc000013c30)
	github.com/jrhouston/tfk8s/tfk8s.go:194 +0x41a
main.main()
	github.com/jrhouston/tfk8s/tfk8s.go:251 +0x35c


⚠️  Oh no! Looks like your manifest caused tfk8s to crash.
```

See https://github.com/argoproj/argo-workflows/blob/master/examples/archive-location.yaml for a real example.

**Comment by jrhouston** [comment]
Ah, this is because we're relying upon a name being in the metadata [here](https://github.com/jrhouston/tfk8s/blob/main/tfk8s.go#L110). I'll update to to also check for `generateName`. Thanks for opening this @lbodor!

**Comment by lbodor** [comment]
Thanks very much.
