### ISSUE TITLE
panic: value is null when trying to work with sample karpenter Provisioner manifest

### ISSUE THREAD

**Issue by blongman-snapdocs** [jrhouston/tfk8s#39]
Tried this with the sample manifest and got a crash in a couple different versions of tfk8s:

```
 $ cat karpenter-provisioner.yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
name: default
spec:
#Requirements that constrain the parameters of provisioned nodes.
#Operators { In, NotIn } are supported to enable including or excluding values
  requirements:
    - key: "node.kubernetes.io/instance-type" #If not included, all instance types are considered
      operator: In
      values: ["m5.large", "m5.2xlarge"]
    - key: "topology.kubernetes.io/zone" #If not included, all zones are considered
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "kubernetes.io/arch" #If not included, all architectures are considered
      operator: In
      values: ["arm64", "amd64"]
    - key: "karpenter.sh/capacity-type" #If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-eks-karpenter-demo
  ttlSecondsAfterEmpty: 30
 $
```
Here is the crash output:
```
 $ /usr/local/Cellar/tfk8s/0.1.7/bin/tfk8s -f karpenter-provisioner.yaml
panic: value is null

goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.capturePanic()
	github.com/jrhouston/tfk8s/tfk8s.go:219 +0x39
panic({0x1173300, 0x11d94f0})
	runtime/panic.go:1038 +0x215
github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x11ddea0, 0x130e6b0}}, {0x0, 0x0}})
	github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1058 +0x1d8
github.com/zclconf/go-cty/cty.Value.AsValueMap({{{0x11ddea0, 0x130e6b0}}, {0x0, 0x0}})
	github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1315 +0x71
main.yamlToHCL({{{0x11ddf48, 0xc000171600}}, {0x117ac40, 0xc00017eb40}}, {0x0, 0x0}, 0x0, 0x0)
	github.com/jrhouston/tfk8s/tfk8s.go:109 +0x2bc
main.YAMLToTerraformResources({0x11da9c0, 0xc0000106a0}, {0x0, 0x0}, 0x0, 0x0)
	github.com/jrhouston/tfk8s/tfk8s.go:194 +0x2d7
main.main()
	github.com/jrhouston/tfk8s/tfk8s.go:251 +0x334


⚠️  Oh no! Looks like your manifest caused tfk8s to crash.

Please open a GitHub issue and include your manifest YAML with the stack trace above,
or ping me on slack and I'll try and fix it!

GitHub: https://github.com/jrhouston/tfk8s/issues
Slack: #terraform-providers on https://kubernetes.slack.com

- Thanks, @jrhouston
```

**Comment by blongman-snapdocs** [comment]
Worked it out.  The example was wrong and name: needed to be indented.
