### ISSUE TITLE
Unable to convert Yaml to terraform

### ISSUE THREAD

**Issue by Prat0487** [jrhouston/tfk8s#42]
I am getting below error while converting YAML to terraform.
Below is my manifest file link 

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/release-1.3/deploy/kubernetes/base/kustomization.yaml

I am getting below error for above manifest

panic: value is null
goroutine 1 [running]:
runtime/debug.Stack(0xc0000a7940, 0x5d4fe0, 0x64b250)
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x9f
main.capturePanic()
        /home/ec2-user/environment/yamtotf/tfk8s/tfk8s.go:234 +0x73
panic(0x5d4fe0, 0x64b250)
        /usr/lib/golang/src/runtime/panic.go:969 +0x1b9
github.com/zclconf/go-cty/cty.Value.LengthInt(0x0, 0x0, 0x0, 0x0, 0xc000018d01)
        /home/ec2-user/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1058 +0x277
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x0, 0x0, 0x0, 0x0, 0x78d4c0)
        /home/ec2-user/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1315 +0x95
main.yamlToHCL(0x652140, 0xc0000d2350, 0x5ddaa0, 0xc000073aa0, 0x0, 0x0, 0x0, 0x0, 0x652140, 0xc0000d2350, ...)
        /home/ec2-user/environment/yamtotf/tfk8s/tfk8s.go:111 +0x2ea
main.YAMLToTerraformResources(0x64ee20, 0xc000010698, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0xc000018a9b, 0xc00004bbe0)
        /home/ec2-user/environment/yamtotf/tfk8s/tfk8s.go:209 +0x41d
main.main()
        /home/ec2-user/environment/yamtotf/tfk8s/tfk8s.go:267 +0x3c5

Please someone who can help me on this or convert above Yaml file to terraform?

**Comment by jrhouston** [comment]
Hi @Prat0487 that looks like a Kustomize YAML – this tool is only for converting the YAML for Kubernetes resources.

**Comment by Zamyatin** [comment]
Hi @Prat0487 I believe what you'd want to do (possibly, if this works for you) is use kustomize to build the manifest(s) for your deployment  - `node-daemonsets`, `serviceAccounts`, etc...  to an outputted yaml file.

This YAML you then feed into this `tfk8s` tool, which would create separate terraform resources for your various resources as defined in the kustomize output.

So: 
1) `kustomize build aws-efs-csi-driver/deploy/kubernetes/base > my_kube_manifests.yaml`
2) `cat my_kube_manifests.yaml | tfk8s > kubernetes_base.tf`

... from here you would probably want to determine what are *required* (base) resources, then mix in some of those overlays as appropriate. 

Basically, the difference is that Terraform is a _templating_ tool, while Kustomize is a _patching_ tool [Victor Farcic covers these tooling types (using Helm as the templating tool in the comparison) in this video](https://technologyconversations.com/2021/01/26/helm-vs-kustomize-the-fight-between-templating-and-patching-in-kubernetes/).  

The same ends can be achieved, that is, getting your resources set up as desired for a given environment, allowing for differentiation between environments... it's just that patching YAML is clean but hard to validate until you push it and it breaks/gets rejected, while Terraform has some verifiability tooling to make sure the intended changes make sense (either through Terraform LSP + your code editor, or through `terraform validate`, though I can't confirm how well `terraform validate` will handle custom K8s manifests or K8s CRDs).

Anyway, out of curiosity I went through the process above and got what I believe you're looking for.  :)
